#!/bin/sh
set -eu

target=/usr/share/nginx/html/runtime-env.js

printf 'window.__APP_CONFIG__ = ' > "$target"
jq -n \
  --arg CORALOGIX_RUM_PUBLIC_KEY "${CORALOGIX_RUM_PUBLIC_KEY:-}" \
  --arg CORALOGIX_RUM_DOMAIN "${CORALOGIX_RUM_DOMAIN:-eu1.coralogix.com}" \
  --arg CORALOGIX_APPLICATION "${CORALOGIX_APPLICATION:-cms-demo}" \
  --arg CORALOGIX_SUBSYSTEM "${CORALOGIX_SUBSYSTEM:-cms-frontend}" \
  --arg CORALOGIX_ORGANIZATION_NAME "${CORALOGIX_ORGANIZATION_NAME:-Acme Digital Works}" \
  --arg CORALOGIX_ENVIRONMENT "${CORALOGIX_ENVIRONMENT:-local}" \
  --arg CORALOGIX_APP_VERSION "${CORALOGIX_APP_VERSION:-dev}" \
  --arg CORALOGIX_RUM_SESSION_SAMPLE_RATE "${CORALOGIX_RUM_SESSION_SAMPLE_RATE:-100}" \
  --arg CORALOGIX_OTLP_TRACES_URL "${CORALOGIX_OTLP_TRACES_URL:-/v1/traces}" \
  '{
    CORALOGIX_RUM_PUBLIC_KEY: $CORALOGIX_RUM_PUBLIC_KEY,
    CORALOGIX_RUM_DOMAIN: $CORALOGIX_RUM_DOMAIN,
    CORALOGIX_APPLICATION: $CORALOGIX_APPLICATION,
    CORALOGIX_SUBSYSTEM: $CORALOGIX_SUBSYSTEM,
    CORALOGIX_ORGANIZATION_NAME: $CORALOGIX_ORGANIZATION_NAME,
    CORALOGIX_ENVIRONMENT: $CORALOGIX_ENVIRONMENT,
    CORALOGIX_APP_VERSION: $CORALOGIX_APP_VERSION,
    CORALOGIX_RUM_SESSION_SAMPLE_RATE: $CORALOGIX_RUM_SESSION_SAMPLE_RATE,
    CORALOGIX_OTLP_TRACES_URL: $CORALOGIX_OTLP_TRACES_URL
  }' >> "$target"
printf ';\n' >> "$target"
