apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cms-demo

resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - kafka-deployment.yaml
  - backend-deployment.yaml
  - backend-serviceMonitor.yaml
  - prometheus-role.yaml
  - media-worker-deployment.yaml
  - frontend-deployment.yaml
  - otel-agent-service.yaml
  - ingress.yaml

commonLabels:
  project: demo-cms
  managed-by: kustomize
