apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cms-demo

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - kafka-deployment.yaml
  - media-worker-deployment.yaml
  - otel-agent-service.yaml
  - network-policy.yaml
  - canvas-backend-deployment.yaml
  - canvas-frontend-deployment.yaml
  - canvas-load-configmap.yaml
  - canvas-load-statefulset.yaml
  - canvas-load-service.yaml
  - ingress.yaml

labels:
  - pairs:
      project: demo-cms
      managed-by: kustomize
    includeSelectors: false
