#!/bin/sh
set -eu

target=/usr/share/nginx/html/runtime-env.js

printf 'window.__APP_CONFIG__ = ' > "$target"
jq -n \
  --arg CORALOGIX_RUM_PUBLIC_KEY "${CORALOGIX_RUM_PUBLIC_KEY:-}" \
  --arg CORALOGIX_RUM_DOMAIN "${CORALOGIX_RUM_DOMAIN:-eu1.coralogix.com}" \
  --arg CORALOGIX_APPLICATION "${CORALOGIX_APPLICATION:-cms-demo}" \
  --arg CORALOGIX_SUBSYSTEM "${CORALOGIX_SUBSYSTEM:-canvas-frontend}" \
  --arg CORALOGIX_ORGANIZATION_NAME "${CORALOGIX_ORGANIZATION_NAME:-Acme Digital Works}" \
  --arg CORALOGIX_ENVIRONMENT "${CORALOGIX_ENVIRONMENT:-local}" \
  --arg CORALOGIX_APP_VERSION "${CORALOGIX_APP_VERSION:-dev}" \
  --arg CORALOGIX_RUM_SESSION_SAMPLE_RATE "${CORALOGIX_RUM_SESSION_SAMPLE_RATE:-100}" \
  --arg CANVAS_LAG_SIM_ENABLED "${CANVAS_LAG_SIM_ENABLED:-}" \
  --arg CANVAS_LAG_SIM_MODE "${CANVAS_LAG_SIM_MODE:-}" \
  --arg CANVAS_LAG_SIM_DELAY_MS "${CANVAS_LAG_SIM_DELAY_MS:-}" \
  --arg CANVAS_LAG_SIM_JITTER_MS "${CANVAS_LAG_SIM_JITTER_MS:-}" \
  --arg CANVAS_LAG_SIM_ALLOW_PROD "${CANVAS_LAG_SIM_ALLOW_PROD:-}" \
  --arg CANVAS_LAG_SIM_RENDER_COST_US "${CANVAS_LAG_SIM_RENDER_COST_US:-}" \
  --arg CANVAS_LAG_SIM_LARGE_BOARD_THRESHOLD "${CANVAS_LAG_SIM_LARGE_BOARD_THRESHOLD:-}" \
  --arg RUM_DEMO_ENABLED "${RUM_DEMO_ENABLED:-}" \
  --arg RUM_DEMO_ALLOW_PROD "${RUM_DEMO_ALLOW_PROD:-}" \
  --arg RUM_DEMO_PANEL "${RUM_DEMO_PANEL:-}" \
  --arg CORALOGIX_RUM_SCREENSHOTS_ENABLED "${CORALOGIX_RUM_SCREENSHOTS_ENABLED:-}" \
  --arg CORALOGIX_RUM_SCREENSHOTS_ALLOW_PROD "${CORALOGIX_RUM_SCREENSHOTS_ALLOW_PROD:-}" \
  --arg CORALOGIX_RUM_SCREENSHOT_THRESHOLD "${CORALOGIX_RUM_SCREENSHOT_THRESHOLD:-}" \
  --arg CORALOGIX_RUM_SCREENSHOT_COOLDOWN_MS "${CORALOGIX_RUM_SCREENSHOT_COOLDOWN_MS:-}" \
  --arg CORALOGIX_RUM_SCREENSHOT_MAX_PER_SESSION "${CORALOGIX_RUM_SCREENSHOT_MAX_PER_SESSION:-}" \
  --arg CORALOGIX_RUM_SCREENSHOT_MAX_ERRORS "${CORALOGIX_RUM_SCREENSHOT_MAX_ERRORS:-}" \
  --arg CORALOGIX_RUM_SESSION_RECORDING_SAMPLE_RATE "${CORALOGIX_RUM_SESSION_RECORDING_SAMPLE_RATE:-}" \
  --arg CORALOGIX_OTLP_TRACES_URL "${CORALOGIX_OTLP_TRACES_URL:-/v1/traces}" \
  '{
    CORALOGIX_RUM_PUBLIC_KEY: $CORALOGIX_RUM_PUBLIC_KEY,
    CORALOGIX_RUM_DOMAIN: $CORALOGIX_RUM_DOMAIN,
    CORALOGIX_APPLICATION: $CORALOGIX_APPLICATION,
    CORALOGIX_SUBSYSTEM: $CORALOGIX_SUBSYSTEM,
    CORALOGIX_ORGANIZATION_NAME: $CORALOGIX_ORGANIZATION_NAME,
    CORALOGIX_ENVIRONMENT: $CORALOGIX_ENVIRONMENT,
    CORALOGIX_APP_VERSION: $CORALOGIX_APP_VERSION,
    CORALOGIX_RUM_SESSION_SAMPLE_RATE: $CORALOGIX_RUM_SESSION_SAMPLE_RATE,
    CANVAS_LAG_SIM_ENABLED: $CANVAS_LAG_SIM_ENABLED,
    CANVAS_LAG_SIM_MODE: $CANVAS_LAG_SIM_MODE,
    CANVAS_LAG_SIM_DELAY_MS: $CANVAS_LAG_SIM_DELAY_MS,
    CANVAS_LAG_SIM_JITTER_MS: $CANVAS_LAG_SIM_JITTER_MS,
    CANVAS_LAG_SIM_ALLOW_PROD: $CANVAS_LAG_SIM_ALLOW_PROD,
    CANVAS_LAG_SIM_RENDER_COST_US: $CANVAS_LAG_SIM_RENDER_COST_US,
    CANVAS_LAG_SIM_LARGE_BOARD_THRESHOLD: $CANVAS_LAG_SIM_LARGE_BOARD_THRESHOLD,
    RUM_DEMO_ENABLED: $RUM_DEMO_ENABLED,
    RUM_DEMO_ALLOW_PROD: $RUM_DEMO_ALLOW_PROD,
    RUM_DEMO_PANEL: $RUM_DEMO_PANEL,
    CORALOGIX_RUM_SCREENSHOTS_ENABLED: $CORALOGIX_RUM_SCREENSHOTS_ENABLED,
    CORALOGIX_RUM_SCREENSHOTS_ALLOW_PROD: $CORALOGIX_RUM_SCREENSHOTS_ALLOW_PROD,
    CORALOGIX_RUM_SCREENSHOT_THRESHOLD: $CORALOGIX_RUM_SCREENSHOT_THRESHOLD,
    CORALOGIX_RUM_SCREENSHOT_COOLDOWN_MS: $CORALOGIX_RUM_SCREENSHOT_COOLDOWN_MS,
    CORALOGIX_RUM_SCREENSHOT_MAX_PER_SESSION: $CORALOGIX_RUM_SCREENSHOT_MAX_PER_SESSION,
    CORALOGIX_RUM_SCREENSHOT_MAX_ERRORS: $CORALOGIX_RUM_SCREENSHOT_MAX_ERRORS,
    CORALOGIX_RUM_SESSION_RECORDING_SAMPLE_RATE: $CORALOGIX_RUM_SESSION_RECORDING_SAMPLE_RATE,
    CORALOGIX_OTLP_TRACES_URL: $CORALOGIX_OTLP_TRACES_URL
  }' >> "$target"
printf ';\n' >> "$target"
