apiVersion: v1
kind: ServiceAccount
metadata:
  name: coralogix-opentelemetry-collector
  namespace: cms-demo
  labels:
    app.kubernetes.io/instance: coralogix-otel-raw
    app.kubernetes.io/name: opentelemetry-cluster-collector
    app.kubernetes.io/part-of: coralogix-infrastructure-explorer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: coralogix-opentelemetry
  namespace: cms-demo
  labels:
    app.kubernetes.io/instance: coralogix-otel-raw
    app.kubernetes.io/name: opentelemetry-agent
    app.kubernetes.io/part-of: coralogix-infrastructure-explorer
