apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: coralogix-opentelemetry-agent
  namespace: cms-demo
  labels:
    app.kubernetes.io/instance: coralogix-otel-raw
    app.kubernetes.io/name: opentelemetry-agent
    app.kubernetes.io/part-of: coralogix-infrastructure-explorer
    app.kubernetes.io/version: "0.142.0"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: coralogix-otel-raw
      app.kubernetes.io/name: opentelemetry-agent
      component: agent-collector
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: coralogix-otel-raw
        app.kubernetes.io/name: opentelemetry-agent
        app.kubernetes.io/part-of: coralogix-infrastructure-explorer
        component: agent-collector
    spec:
      serviceAccountName: coralogix-opentelemetry
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/os: linux
      tolerations:
        - operator: Exists
      containers:
        - name: opentelemetry-agent
          image: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-contrib:0.142.0
          imagePullPolicy: IfNotPresent
          command:
            - /otelcol-contrib
            - --config=/conf/relay.yaml
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: KUBE_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: K8S_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: GOMEMLIMIT
              value: 1525MiB
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment.name=cms-demo-cluster
            - name: KUBE_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: CORALOGIX_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: coralogix-keys
                  key: PRIVATE_KEY
          ports:
            - name: otlp
              containerPort: 4317
              hostPort: 4317
              protocol: TCP
            - name: otlp-http
              containerPort: 4318
              hostPort: 4318
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 13133
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 13133
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: "1"
              memory: 2Gi
          securityContext:
            privileged: true
            runAsUser: 0
            runAsGroup: 0
          volumeMounts:
            - name: opentelemetry-agent-configmap
              mountPath: /conf
            - name: varlogpods
              mountPath: /var/log/pods
              readOnly: true
            - name: varlibdockercontainers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: hostfs
              mountPath: /hostfs
              readOnly: true
              mountPropagation: None
      volumes:
        - name: opentelemetry-agent-configmap
          configMap:
            name: coralogix-opentelemetry-agent
            items:
              - key: relay
                path: relay.yaml
        - name: varlogpods
          hostPath:
            path: /var/log/pods
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - name: hostfs
          hostPath:
            path: /
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
